### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by TheKnarf** [TheKnarf/HeliumAnion#1]
The project needs a logo.

The project name is based on physics, where Helium is the second Atom in the periodic table, and an Anion is a negatively charged ion. The project is also an reimplementation of the [Helium app](https://heliumfloats.com/) using [Electron](https://electronjs.org/). So maybe a logo inspired by those two products logo combined.

Inspiration:
![helium_logo](https://user-images.githubusercontent.com/213777/60524991-de2a3100-9ced-11e9-9fc1-2786b35d0c1c.png)

![Screenshot 2019-07-02 at 17 22 18](https://user-images.githubusercontent.com/213777/60525050-f8640f00-9ced-11e9-981b-7ccf42cde8ca.png)

**Comment by munadikieh** [comment]
Dear Sir/ Madam,
Hi, I'm Graphic Designer. I want to contribute to this project by creating new logo.  I have design sample of logo for HeliumAnion, is there anything you want to change, please let me know.
![Artboard 2](https://user-images.githubusercontent.com/41304326/60917885-1ddbb480-a2bc-11e9-977f-4298d04a0e26.jpg)

**Comment by TheKnarf** [comment]
@munadikieh I love it! That looks absolutely amazing!

I sent you an email to the address stated on your profile :-)
